# To change this template, choose Tools | Templates
# and open the template in the editor.
{
        "name" : "Meetings",
        "version" : "0.1",
        "author" : "Bista Solutions",
        "website" : "http://openerp.com",
        "category" : "Unknown",
        "description": """  """,
        "depends" : ['base','sale','product','account','stock','crm','stock_location'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "update_xml" : [
            'security/sale_security.xml',
            'security/ir.model.access.csv',
            'report/report_stock_move_view.xml',
            'res_partner_view.xml',
            'res_partner_tree_view.xml',
            'meeting_view.xml', 
            'product_view.xml',
	    'partner_view.xml',
	    'partner_view_imp.xml',
	    'sale_view.xml',
            'customer_check_data.xml',
	    'crm_phonecall_view.xml',
            'wizard/sales_analysis_view.xml',
            'wizard/stock_import_csv.xml',
            'wizard/stock_change_price_view.xml',
            'wizard/return_products_move.xml',
            'wizard/sale_order_lines.xml',
            'wizard/consignment_price_view.xml',
            'wizard/stock_level.xml',
            'stock_view.xml',
            'kalpa_stock_move_report.xml',
            'account_view.xml',
	    'product_tree_view.xml',
	    'crm_lead_tree_view.xml',
            'menu_view.xml',
            ],
        "installable": True
}
